# Generated by Django 4.1.1 on 2022-10-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_book_name_books_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
